name: Bug
description: Presenta un informe de un error.
title: "[Bug]: "
labels: ["bug"]
projects: ["intelinet-last"]
assignees:
  - octocat
body:
  - type: input
    id: name
    attributes:
      label: Nombre de quien reporta
      description: Nombre de la persona o usuario que ha reportado el bug.
      placeholder: Ej. Jorge Trejo
    validations:
      required: true
  - type: input
    id: phone
    attributes:
      label: Número de contacto o WhatsApp
      description: Algún medio de contacto por si necesitamos más información.
      placeholder: Ej. 6145202020
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: ¿Qué ha pasado?
      description: Díganos también, ¿qué esperaba que ocurriera?
      placeholder: Díganos lo que ve.
      value: "Se ha producido un error"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: ¿En qué navegadores se produce el problema?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Brave
        - Safari
        - Microsoft Edge
        - Arc
    validations:
      required: true
